version: '3.9'
services:
  web:
    image: php:apache
    container_name: php_web
    depends_on:
      - db
    volumes:
      - ./php/:/var/www/html/
    ports:
      - '8100:80'

  db:
    image: mysql:5.7
    container_name: mysqldb
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_USER: user1
      MYSQL_ROOT_PASSWORD: P@ssw0rd
      MYSQL_PASSWORD: P@ssw0rd
      MYSQL_DATABASE: test

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - '8081:80'
    environment:
      - PMA_ARBITRARY=1
    depends_on:
      - db
